language: node_js
node_js:
  - node
script:
  - yarn install
  - yarn global add bower
  - bower install
  - yarn build
deploy:
  provider: gcs
  access_key_id: $GCS_ACCESS_KEY_ID
  secret_access_key: $GCS_SECRET_ACCESS_KEY
  bucket: "hcloud-rancher-v1-ui-driver"
  acl: public-read
  skip_cleanup: true
  local-dir: dist
  on:
    branch: v1.6