language: node_js
node_js:
  - node
script:
  - yarn global add bower
  - bower install
  - yarn build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: dist
branches:
    only:
    - master